# Generated by Django 2.2.16 on 2021-01-11 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0023_remove_message_recaptcha'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='upwork',
            field=models.URLField(blank=True, null=True),
        ),
    ]
